### ISSUE TITLE
Doesn't support 24H time

### ISSUE THREAD

**Issue by robertjskelton** [Nannoises/PokeBattleColor#3]
This watchface doesn't support 12H/24H time. It should get which format the watch requests and use that, but this one always uses 12H. I use 24H, so this bugged me enough to download the Pebble SDK and find a solution, a good link is here: http://developer.getpebble.com/guides/pebble-apps/app-events/tick-timer/#how-to-use

This is on Line 514 of pokebattlecolor.c, should be changed to something similar that the example provides. I just changed %I to %H since I only want 24H format.

**Comment by Nannoises** [comment]
This is now fixed. Will hopefully be releasing a new version soon.
